facebookresearch/nle

nle/agent/agent.py
Could have moved the whole env + torch import bit down instead, but there's a chance we set the imports this way to avoid import bugs wrt gym and torch, so better to be conservative with these changes until we can confirm otherwise.
=> Disable E402 for imports in agent.py

sys/unix/hints/macosx
Alternative: Output of `xcodebuild -find cc`, but we will call `make`
anyway hoping it's the right version.
Hope this might fix #28 .
=> Explicitly ask for clang in hints/macosx.

sys/unix/hints/macosx-nle
This is to further patch out #28 for today's release.
=> Set clang as linker on MacOS

.github/workflows/build_docker.yml
Sigh. Left a debugging instruction which stops one of the docker CI pushes. Removing it here.
=> Remove unnecessary check in CI

.github/workflows/build_docker.yml, docker/Dockerfile, docker/Dockerfile-xenial
And build images on PR events too, so that next time we will know if the workflow is broken.
Previous PR broke CI on master, since the docker image workflows didn't get run. This PR allows to run _some_ of the workflow, up till before pushing any image, on PR events. Hopefully this will prevent any other such mistakes.
As a good side effect, this PR also allows any PR tracking a branch of a forked repo to build docker images (since the jobs won't explode anymore because of the dockerhub not being available in the CI context).
=> Clone repository recursively in CI when building docker images

.gitignore, CMakeLists.txt, README.md, doc/nle/source/getting_started.rst, docker/README.md, nle/nethack/nethack.py, setup.py
This PR modifies `setup.py` to install `HACKDIR` into the package, allowing to use `pkg_resources` to find it at runtime, as well as allowing `pip` to remove it when uninstalling the package.
When installing the package in editable mode, `HACKDIR` will be equal to `nle/nethackdir`.
=> Install HACKDIR into package

nle/agent/agent.py
This is OS dependent (mail daemon etc). We should really start doing a better featurization (cf. #21).
=> Use nethack.MAX_GLYPH instead of magic constant.

nle/dashboard/package-lock.json
The gift that keeps giving. Why do we require dozens of npm packages?
Reference(s):
https://www.npmjs.com/advisories/1523
https://github.com/advisories/GHSA-p6mc-m468-83gw
=> Fix lodash version due to GHSA-p6mc-m468-83gw.

CMakeLists.txt
Upgrading from cmake version 3.13.1 made this error go away:
CMake Error at CMakeLists.txt:67 (install):
install TARGETS given no RUNTIME DESTINATION for executable target
"nethack".
=> Require cmake version >= 3.14

nle/env/base.py, nle/tests/test_envs.py
This adds "chars", "colors", and "specials" as observation keys. The latter is an xor'ed version of
```c
#define MG_CORPSE  0x01
#define MG_INVIS   0x02
#define MG_DETECT  0x04
#define MG_PET     0x08
#define MG_RIDDEN  0x10
#define MG_STATUE  0x20
#define MG_OBJPILE 0x40  /* more than one stack of objects */
#define MG_BW_LAVA 0x80  /* 'black & white lava': highlight lava if it
can't be distringuished from water by color */
```
(see hack.h)
This PR adds them as individual uint8 tensors. We could also return something of shape [3, DUNGEON_HEIGHT, DUNGEON_WIDTH]?
=> Enable chars, colors, specials as observation tensors.

dat/CMakeLists.txt
It turns out both makedefs -e and -s create & destroy dat/grep.tmp.
This file creation & deletion can raise. This change hacks it to be
linearized.
This issue mainly shows up when using ninja (>> make).
=> Introduce hack to fix a race in the makedef runs.

dat/CMakeLists.txt
**Previously, we had a too-small `nhdat` file and the game would crash or otherwise get into a bad state as soon as we entered e.g. the Gnomish mines.**
This has been the case since we switched to cmake, but it wasn't easy to detect as we need agents that get as far first.
This fixes the cmake logic to produce a `nhdat` with all required files.
**However**, I don't necessarily like that we build everything in the source directory. We should fix dat/CMakeLists.txt to copy the source dat/ directory into the build directory and run all commands there. I suspect this may make the logic in this file easier.
=> Very important fix: nhdat did not contain all files necessary.

CMakeLists.txt, nle/tests/test_nethack.py, win/rl/pynethack.cc
This is a bit more complicated than permonst as the user can
"name" and "discover" an object and hence change it. This here does
not interact with any real running NetHack, so these fields won't
change and/or have any real information.
=> Add objclass and objdescr as Python classes.

CMakeLists.txt, MANIFEST.in, dat/CMakeLists.txt, nle/nethack/nethack.py, nle/scripts/patch_nhdat.sh, util/CMakeLists.txt
Using those, we can define our own custom levels, e.g.
1. Use the tar-like tool `dlb` to extract `nhdat`.
2. Add a `mylevel.des` file as per `5. Creating a new level` in
https://nethackwiki.com/wiki/Beginner%27s_guide_to_NetHack_sources
(the .des files are part of the NLE installation, but not in `nhdat` as they are sources).
3. Compile that file using `lev_comp`, producing `mylevel.lev`.
4. Add the new level to `dungeon.def` (also part of the NLE installation).
5. Run `makedefs -e` and `dgn_comp dungeon.pdf` to produce `dungeon`.
6. Re-assemble the new set of files using `dlb` which includes `dungeon` and `mylevel.des`.
From patch_nhdat.sh in this commit:
```sh
HACKDIR=$(python -c 'import pkg_resources; print(pkg_resources.resource_filename("nle", "nethackdir"), end="")') …
```
=> Install the nethack util binaries and their documentation.

.github/workflows/test_and_deploy.yml, .github/workflows/test_package.yml, README.md, doc/nle/source/getting_started.rst, docker/Dockerfile, docker/Dockerfile-xenial, sys/unix/Makefile.src
Remove all mentions of `zmq`/`zeromq` and `flatbuffers` as we no longer depend on those libraries.
=> Update README, docs, GitHub workflows, Dockerfiles.

nle/scripts/ttyplay.py
This change makes `l` in `nle-ttyplay` work again (for skipping forward).
It also supports playing bzip2'd and gzip'ed input files.
=> New ttyplay features

.circleci/config.yml, CMakeLists.txt, README.md, include/nle.h, include/unixconf.h, nle/env/base.py, nle/nethack/nethack.py, nle/scripts/play.py, nle/tests/test_envs.py, src/nle.c
* Setting the terminal size makes sure our ttyrecs will be 80x24, which is both the minimum size and the size of the majority of ttyrecs on alt.org
* Writing bzip2'd ttyrecs should save up to 80% of disk space. Only downside is that we can no longer peek into running ttyrecs this way, which was sometimes useful for debugging. To go back to that mode, we can `#undefine NLE_BZ2_TTYRECS`.
=> Fix terminal size at 80x24, write bzip2'ed ttyrecs

nle/env/base.py
Useful for testing when selecting items in the inventory. Have no idea how to test this programmatically, but I did test this with play.py.
=> Add inv letter to rendering.

nle/scripts/read_tty.py, nle/scripts/ttyrec.py
Impression on how the `read_tty.py` output looks now:
See https://github.com/deadpixi/libtmt#supported-input-and-escape-sequences and https://en.wikipedia.org/wiki/DEC_Special_Graphics for details on what these things mean.
=> Terminal ttyrec stuff

include/nleobs.h, nle/env/base.py, nle/nethack/nethack.py, nle/tests/test_nethack.py, win/rl/pynethack.cc, win/rl/winrl.cc
Our representation of a single observation does not capture all of the information of the game state that is available to the user. For instance, information on whether an object is greased, rusted, blessed or cursed is only conveyed through text, often by 'glancing' at the map (';' action). Similarly, if there are many items on a map, a glyph id cannot convey that though text can ('many objects here').
This pull request adds an observation that is the equivalent of 'glancing' at every square on the map, before returning, with auto describe on.
The big concern here is the performance implications of copying across upto 80 dungeons worth of data at a time.  Due to the nle architecture, you only pay for what you need (nice @heiner !) so this would only hit people who need the observation, …
=> Add text descriptions as an observation for each object on the map.

win/tty/wintty.c
=> Don't call setbuf on stdout in NLE

win/rl/pynethack.cc
It turns out I misunderstood what pybind11's py::array::ensure does.
Looking at the code superficially (https://github.com/pybind/pybind11/blob/master/include/pybind11/numpy.h#L785)
I assumed this function steals a reference, hence the call to
release(). But the reference is being stolen from the return value
of raw_array(), which returns a new reference. Hence ensure() itself
does not steal anything but in fact increases the refcount (and will
decref it in ~array).
Thanks to @yobibyte for both finding this issue and insisting that
it happens on the Python side (I thought this might be related to
malloc calls in NetHack itself).
=> Fix a bad memory leak.

setup.py
In some rare cases, CMake can insist on using a different Python
version than the one that runs setup.py at the moment. This change
should prevent that.
=> Use same running Python version in CMake.

CMakeLists.txt, docker/Dockerfile, include/config.h, nle/scripts/play.py, nle/scripts/read_heaplog.py, src/nle.c, sys/unix/nledl.c, sys/unix/rlmain.cc, win/tty/termcap.c
Fix a termcap/terminfo/termlib/ncurses related memory leak.
Even after recent fixes, we were still seeing memory leaks. This
commit fixes another one.
The terminfo/termcap library is a weird 1980s mess. Among other
things, it cannot clean up after itself. The tgetent(3) call allocs
some memory; it also sets some global state that tells it to re-use
that memory in future calls (most programs will call tgetent only
once; NLE and screen/tmux might be exceptions).
However, or dlopen/dlclose trick dynamically loaded AND UNLOADED
libncurses, which probably reset its global state, creating new
memory allocations for each tgetent call. Or perhaps calling tgetent
several times just leaks in every case.
This change moves the tgetent call up one level into nledl.c, and
only does it once (per …
=> Fix ncurses-related memory leak; various updates to help debugging

CMakeLists.txt, docker/Dockerfile.valgrind, include/config.h, include/tcap.h, sys/unix/nledl.c, sys/unix/rlmain.cc, win/tty/termcap.c
This PR removes ncurses as a dependency. It also makes for a nice Valgrind output:
```sh
nle$ docker build -t nle -f docker/Dockerfile.valgrind .
nle$ docker run --rm --name nle nle
==7== Memcheck, a memory error detector
==7== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==7== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==7== Command: ./rlmain r
==7== Parent PID: 1
==7==
==7== Warning: client switching stacks?  SP change: 0x1ffeffe6a8 --> 0x5977fc0
==7==          to suppress, use: --max-stackframe=137328355048 or greater
==7== Warning: client switching stacks?  SP change: 0x5977a88 --> 0x1ffeffe6a8
==7==          to suppress, use: --max-stackframe=137328356384 or greater
==7== Warning: client switching stacks?  SP change: 0x1ffeffe678 --> …
```
=> Drop ncurses

.github/workflows/build_docker.yml, docker/Dockerfile-bionic, docker/Dockerfile-focal, docker/Dockerfile-xenial, docker/README.md
build xenial properly and remove ncurses dependency.
=> Add Dockerfile for Ubuntu 20.04 (focal fossa). Also fixup docker file to

nle/scripts/check_nethack_speed.py, nle/tests/test_nethack.py, nle/tests/test_profile.py, setup.py
This PR involves 2 fixes. 
* 1st a fixup to `check_nethack_speed` to ensure it runs. Sadly as its not hooked into any automated tests I think it just got a bit out of sync with the API.
* 2nd is an introduction of a profiling test using pytest-benchmark. I think this set up will allow us to effectively and (relatively) reliably measure SPS for our code changes. The output of such a pytest-benchmark is very also informative - note the OPS column gives us the mean kilo-steps-per-second.  
Well it seemed to me that the former script didn't really measure the steps per second of a single environment, rather the maximum throughput one could get running all the environments in suprocesses and putting the number of steps in a shared queue (which could be still useful!).
To illustrate my point …
=> Add benchmarks sps profile test.

win/rl/winrl.cc
Having profiled the code using the tests presented in PR #130 , it became clear the performance of the screen descriptions was adding some quite considerable hits, not just to its own observation keys but everyone.  Below are two commits, offering two solutions - I prefer the last which is the fastest.
This commit does two things: First it only gets screen_desriptions from nethack if they are asked for, and secondly, it uses `strncpy` instead of a for loop. Each of these changes is pretty significant, the former adding 2-3ksps to everyone's performance and the latter adding the same just to screen_descriptions obskey environments.  The price paid is a rather ugly access of the global observation object in the function, but the performance improvement is significant.
This commit replaces …
=> Improve performance 

.github/workflows/test_package.yml, nle/nethack/nethack.py
The current `test_package.yml` workflow test has been broken for 4 months.  I assume it aims to test the nle packages from PyPI but it seems a bit confused, since there is a clone step in it.  Furthermore I cant tell if the purpose of this workflow changed, since the description of the key installation step changed from 'Install from repo in test mode" to  "Install nle via pip" a few months ago to accurately reflect the executed command. Perhaps this was a copy job from a workflow that tests installation from the repo?
At any rate the workflow was failing due to the fact that the cloned local `nle` was being accessed in the final step and it doesnt have the pynethack built, since nle was installed via pip.  Removing the cloned repo has the desired effect.
[Old …
=> Fixup the test PyPI install workflow.

README.md
Current stack trace
```
python -m nle.scripts.play --env nethack
Traceback (most recent call last):
File "/private/home/sodhani/.conda/envs/nle/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/private/home/sodhani/.conda/envs/nle/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/private/home/sodhani/.conda/envs/nle/lib/python3.8/site-packages/nle/scripts/play.py", line 238, in <module>
main()
File "/private/home/sodhani/.conda/envs/nle/lib/python3.8/site-packages/nle/scripts/play.py", line 234, in main
play(**vars(flags))
File "/private/home/sodhani/.conda/envs/nle/lib/python3.8/site-packages/nle/scripts/play.py", line 82, in play
env = gym.make(env_name, savedir=savedir, max_episode_steps=max_steps) …
```
=> Fix the name of the environment in README

nle/env/base.py
I made it a tuple to protect the default object from modification.
=> Make space_dict global to reuse outside nle.

.gitmodules
Git protocol requires ssh + auth in most cases, so it is best to pull any public submodules using https.
=> Set libtmt submodule url to use https

src/nle.c
tty_colors had an unusual range perhaps intended to be [-16, 16), but ended up being... something strange.
This changes it to be [0, 32).
Seeing as nothing really uses this yet, it should be safe to change.
=> Rerange tty_colors to [0, 32)

win/rl/winrl.cc
This method replaces tty_ngetch, and does not call it as per the comment, but it leaves out some important code (ref https://github.com/facebookresearch/nle/blob/master/win/tty/wintty.c#L3486-L3538). This PR adds this code to the winrl getch.
The bug is that if you press escape on a --more-- prompt, WIN_STOP would be set (as a signal to escape from the more prompt and skip any proceeding messages), and this flag would be reset in tty_getch. Without this reset, nle proceeds to skip *every* message in the entire game from that point on, with no recovery (this means no messages are displayed, not even "it's a wall" etc).
the toplin code is part of a tty state machine  in topl.c related to multi-line messages and more prompts, and while I can't entirely figure out the consequence of removing …
=> Fix bug in winrl getch which makes messages disappear forever

.pre-commit-config.yaml
If you install `nle` using the installation guide for the developer mode, then you are running into the following pre-commit error for black. This is because the conda environment in the guide is python3.8, not python3.7.
```
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
```
Updating the `.pre-commit-config.yaml` to python3.8 solves the problem.
=> pre-commit for python3.8

docker/Dockerfile.valgrind, nle/env/base.py, src/nle.c, win/tty/termcap.c
Cherry-pick upstream fix https://github.com/NetHack/NetHack/commit/e7e07cb067c5e6ebda4d9d60ad2d27fc0cb515b7.
This change by PatR was in response to our PR at
https://github.com/NetHack/NetHack/pull/411 and fixes an issue
with "(null)" on MacOS.
Purpose of cherry-picking this is to get this MacOS fix and also
diverge less from upstream NetHack.
Checked via valgrind (on Linux) and does not appear to have malloc leaks this way either.
=> Cherry-pick upstream fix e7e07cb0.

CMakeLists.txt, setup.py
It seems a recent version of cmake (happened to me for cmake 3.20.0)
no longer installs nethackdir when called with
cmake --build . --target install
Starting from cmake 3.15, the command
cmake --install .
works instead (https://stackoverflow.com/a/56457739/1136208).
Fixes issues along the lines of
$ pip install -e .
$ python -m nle.scripts.play
FileNotFoundError: Couldn't find NetHack installation at '/Users/hnr/miniconda3/envs/extdev/lib/python3.8/site-packages/nle/nethackdir
=> Change cmake install command.

nle/env/base.py, nle/env/tasks.py
In standard RL often the reward function takes as input the action
taken. This change allows that to happen by adjusting _reward_fn.
See issue https://github.com/facebookresearch/nle/issues/155 for more details
Closes #155
=> Change _reward_fn to take action taken

nle/env/tasks.py
The internal counter needs to reset when reset() is called, otherwise as soon as it triggers it will also trigger immediately on turn 1 for the next games (breaking NLE entirely).
I've verified that the no progress timeout works as intended with this fix.
=> Fix NetHackChallenge no_progress_timeout

.github/workflows/lint_cc.yml, .pre-commit-config.yaml, CMakeLists.txt, include/config.h, include/nleobs.h, nle/env/tasks.py, nle/scripts/run-clang-format, nle/tests/test_envs.py, nle/tests/test_nethack.py, nle/tests/test_profile.py, src/nle.c, sys/unix/nledl.c, win/rl/pynethack.cc, win/rl/winrl.cc
This PR fixes our C++ lint test (which apparently never really worked and at any rate was broken for months now) and flat-out disables seeding in NLE. The seeding commit is rather defensive for purposes of the NLE competition. Afterwards, we can `#define NLE_ALLOW_SEEDING 1` to turn on the old behaviour.
=> Some fixes to NLE and the competition task

win/rl/winrl.cc
Prior to this commit, the glyph id for a 'Scroll of Identify' always had the same id. 
After this commit, the glyph id for a scroll called 'KERNOD_WELL' always has the same id. 
This mirrors the behaviour of tiles (for builds that use them).
=> Observations in 'glyphs', 'inv_glyphs' now fixed to correspond to description of an object class instead of the name of object class.

include/nleobs.h, nle/env/base.py, nle/env/tasks.py, nle/nethack/nethack.py, nle/tests/test_nethack.py, win/rl/pynethack.cc, win/rl/winrl.cc
Indicators are (yn function, getline or xwaitforspace). Add this observation to NetHackChallenge.
This observation is an array of ints that can later be expanded to more
data if necessary, although the current entries are booleans (0 or 1).
~Tests inbound.~ Tests shipped.
=> Create 'misc' observation with input mode indicators 

nle/agent/agent.py, nle/env/base.py
savedir is a feature that will save ttyrecs of runs - this can be unexpected when training a model and may write a *huge* amount of unwanted files.
This changes the default to *not* save ttyrecs.
If you want ttyrecs to be saved, please specify savedir when instantiating the env from now on.
`archivefile` is a parameter that may have been used at some point, but is currently unused, so let's remove it.
=> Default savedir to None (and remove unused archivefile)

include/nleobs.h, win/rl/winrl.cc
Otherwise, new x, y locations and dlevel will show up on the turn
that says "You descend the stairs.--More--", introducing a difference
between tty_chars and blstats.
=> Update blstats only at end of bot() round.

nle/tests/test_nethack.py, win/rl/winrl.cc
Write moves / time every normal step.
This fixes a bug introduced by dropping the "time" option.
Hopefully fixes #195.
=> Fix blstats, again, again

nle/env/base.py, nle/scripts/play.py, win/rl/pynethack.cc
Also fix `savedir` docstring, make play.py able to do `savedir=None`.
Also also update pybind11 version to 2.6.2.
=> Be less silly, no more `std::unique_ptr<std::FILE, int (*)(std::FILE *)>`

CMakeLists.txt, dat/CMakeLists.txt, include/config.h, include/extern.h, nle/nethack/nethack.py, nle/tests/test_nethack.py, nle/tests/test_profile.py, src/nle.c
Also don't use `sysconf`, which is saner than carrying it around and goes along well with this change.
Misc. fixes to tests.
Fixes #132 and (hopefully!) #193.
=> Don't chdir in NLE

nle/scripts/read_tty.py
I think for some python versions, ints arent automatically converted to strings
```python
Traceback (most recent call last):
File "/home/ubuntu/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/ubuntu/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/nle/scripts/read_tty.py", line 70, in <module>
data = re.sub(r"\\x1b\[([0-9];?)*.", lambda m: color(m.group(0), 8), data)
File "/home/ubuntu/anaconda3/lib/python3.7/re.py", line 192, in sub
return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```
=> Fix minor string issue

.github/workflows/build_docker.yml
Adding this tag means we can do `docker pull fairnle/nle-xenial` and the
`latest` tag will be selected, instead of having to specify `docker pull
fairnle/nle-xenial:v0.7.2` etc.
=> Change `stable` to `latest` tag for our docker images.

nle/nethack/nethack.py
I wonder how this even worked before? At any rate this seems obviously
necessary.
Fixes  https://github.com/facebookresearch/nle/issues/222.
=> Create empty "record" file in NLE's HACKDIR.

CMakeLists.txt, include/nleobs.h, nle/tests/test_envs.py, setup.py
Uses an environment variable called `NLE_DISABLE_SEEDING` to disable seeding in NLE. If it is not set (which is usually expected), seeding is enabled.
Here are the commands I used to test the functionality
```bash
$ pip install -e .
$ python -c 'import gym; import nle; env = gym.make("NetHackScore-v0"); env.reset(); print(env.seed(1))'
(1, 5336406323662859033, False)
$ export NLE_DISABLE_SEEDING=1
$ pip install -e .
$ python -c 'import gym; import nle; env = gym.make("NetHackScore-v0"); env.reset(); print(env.seed(1))'
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/samvelyan/workspace/NLE_fb/nle/nle/env/base.py", line 533, in seed
self.env.set_initial_seeds(core, disp, reseed)
File "/Users/samvelyan/workspace/NLE_fb/nle/nle/nethack/nethack.py", line …
```
=> Disabling seeding in NLE using an environment varariable

nle/scripts/read_tty.py, nle/tests/test_nethack.py, src/nle.c, win/rl/winrl.cc, win/tty/termcap.c
Handle black items correctly.
When using `ANSI_DEFAULT`, `hilites[CLR_BLACK]` was set as a `NULL` string. This caused black items to show up as gray. I sent a fix to upstream NetHack at https://github.com/NetHack/NetHack/pull/556.
Fixing that alone doesn't unbreak `test_nethack.py::TestNethackTerminalObservation::test_crop` (which broke whenever black items were in sight) since `CLR_BLACK` is 0, not 8 aka bright black (and also `NO_COLOR`, somewhat confusingly).
We fix this by changing the output of `mapglyph` for glyphs that aren't the null glyph.
Fixes #198.
Also fix `read_tty.py` (broken after https://github.com/facebookresearch/nle/pull/217) and simplify test_crop.
=> Fix black color handling

nle/nethack/nethack.py
If `memfd_create` is unavailable, try using `O_TMPFILE` via `tempfile.TemporaryFile`.
MacOS has no `memfd_create` or `O_TMPFILE`. Unfortunately, using `/dev/fd/{FD}` as an argument to `dlopen` doesn't work either after unlinking from the file system (see https://gist.github.com/heiner/5179ccaef983b318c1fc451d7efbe95d#file-tmp_memfs_mac-py). So let's copy instead and hope vardir gets properly deleted at some point.
=> Use memfd_create + /proc/self/fd/{FD} for temporary DL on Linux.

win/rl/pynethack.cc
Removing extra whitespace from BL_MASK_STRNGL and BL_MASK_TERMILL so that they export correctly to Python.  Credit to EulersApprentice for catching this problem.
Original problem report:
```
EulersApprentice — Today at 5:30 PM
All of the constants seem to work... except BL_MASK_STRNGL and BL_MASK_TERMILL, which both give the following error:
AttributeError: module 'nle.nethack' has no attribute 'BL_MASK_STRNGL'/'BL_MASK_TERMILL'
Looking at the constants in botl.h, I don't think I'm misspelling them? Or maybe the constants are defined in a different place from where I'm looking, and are spelled differently in that other place?
Stranger still is the fact that my IDE lets me tab-autocomplete nethack.BL_MASK_STRNGL and BL_MASK_TERMILL, but then it still gives me the same error.
```
=> Removing extra whitespace from BL_MASK_STRNGL and BL_MASK_TERMILL

win/rl/pynethack.cc
Exposing the difficulty attribute of the `permonst` struct
Resolves #235
=> Expose Monster Difficulty attribute of permonst struct through FFI

include/config.h
This got auto-enabled when we disabled syscf.
Fixes #239.
=> Disable dumplog files.

nle/nethack/__init__.py
The `INV_SIZE` global variable wasn't exposed for some reason - just exposing it here
=> Expose Inventory Size

nle/nethack/nethack.py
This is triggered in the test_illegal_filename test in test_nethack.py.
=> Run finalizer correctly even when _pynethack.Nethack creation fails.

nle/scripts/plot.py
@heiner Solves #257 
Taken [from here](https://gist.github.com/heiner/c82cfef7cc368b02fd831595f3a1435f)
=> Update plotting script to include xkey and ykey

nle/env/__init__.py
This is an alternative to https://github.com/facebookresearch/nle/pull/269 to fix #272.
----
The most recent version of gym wraps environments with the `OrderEnforcing` wrapper (https://github.com/openai/gym/blob/master/docs/wrappers.md) if not disabled. This breaks our [tests](https://github.com/facebookresearch/nle/pull/268/checks?check_run_id=3821174783), `play.py` and a number of other places. For instance, `env.seed()` with more than 1 argument now also fails due to [`gym.Wrapper.seed`](https://github.com/openai/gym/blob/master/gym/core.py#L300). Possible fixes:
* Use `env.unwrapped` when arguments to `seed` are given
* Disable the `OrderEnforcing` wrapper. This will break NLE when using earlier versions of the gym library unless we do per-version magic (as in this PR). We cannot …
=> Alternative fix for gym 0.21 changes.

nle/env/base.py
(Should not be merged before the end of the NetHack competition.)
This removes the as-far-as-I-know unused `space_dict` argument to the `NLE` class.
For a brief discussion, see https://github.com/facebookresearch/nle/commit/e8597298fe91f8335c86e5cd2b932751248d3f48#commitcomment-56904804
=> Remove space_dict argument to NLE.

nle/tests/test_nethack.py, win/rl/pynethack.cc
This allows us to generate a names of glyphs as in https://github.com/NetHack/NetHack/issues/634#issuecomment-970783123. For example with this code: https://gist.github.com/c5117ed04851c50744779af81825c899
=> Add def_oc_syms to pynethack.cc

include/nle.h, include/nledl.h, include/nleobs.h, nle/nethack/nethack.py, nle/tests/test_envs.py, src/allmain.c, src/files.c, src/mklev.c, src/mkmaze.c, src/mkroom.c, src/nle.c, src/options.c, src/sp_lev.c, sys/unix/nledl.c, sys/unix/rlmain.cc, win/rl/pynethack.cc
This also gets rid of the need to write a file for WIZKIT.
Fixes the race condition in https://github.com/facebookresearch/nle/issues/287
=> Add nle_settings to nledl interface, don't use environment variables

nle/agent/agent.py, nle/env/base.py
=> Add option to save ttyrec files every "M" episodes

nle/env/base.py, nle/env/tasks.py, nle/nethack/nethack.py, nle/tests/test_envs.py, nle/tests/test_profile.py
Fixes #273.
One reason this matters more than one would assume is that gym envs wrappers tend to forward non-underscore access but will typically fail with `._underscore` access. This happened e.g. for the 0.21 release which auto-wrapped every env.
Also a bit more cleanup.
=> Fix _underscore access, rename Nethack variable as `nethack`.

nle/agent/agent.py, nle/env/base.py, nle/tests/test_envs.py
Taking over from https://github.com/facebookresearch/nle/pull/260. Fixes #256.
=> Add option to save ttyrec files every "M" episodes (#260)

nle/tests/test_nethack.py, win/rl/pynethack.cc
This guarantees we write to the buffer from before and therefore
need to only update the delta, saving us a few memcopies potentially.
Fixes #133.
=> Don't allow set_buffers to be called after reset.

nle/nethack/nethack.py, nle/tests/test_nethack.py
A NetHack option like "name:Heiner-@" only selects a random role but
still asks about race/gender/alignment. NetHack also has the command
line flag -@ (mapped to flags.randomall) to randomize everything,
but there's no option in the .nethackrc sense for that.
This change makes it such that playername="Heiner-@" appends
race:random, gender:random, align:random to NetHack's options unless
these have been set already.
Note: In the NetHack competition, this issue didn't hurt us because
we auto-selected "Random" for the startup questions.
Fixes #282.
=> Pick random race/gender/alignment when selecting random role.

dat/CMakeLists.txt
This aligns our NLE cmake files with my proposal for a CMake-based NetHack-build, [here](https://github.com/NetHack/NetHack/pull/662) and [here](https://github.com/heiner/NetHack/tree/NetHack-3.6-cmake). In particular it adds some defensive measures when building NLE with cmake after building some artefacts with NetHack's Makefile setup.
The change in of not using `$<TARGET_FILE:...>` generators as the `COMMAND` of `add_custom_command` comes from [feedback from a PR for NetHack](https://github.com/NetHack/NetHack/pull/662#discussion_r793109922).
=> Updates to cmake

sys/unix/nledl.c, sys/unix/rlmain.cc
This is the issue in #254.
This PR doesn't fix that issue but makes the error less mysterious. One hypothesis of the underlying cause is that all our copies of the .so have the same [dyld UUID](https://github.com/PureDarwin/dyld/blob/56cd028e61d0d487e5b604eb6bd2c5d577b24241/dyld3/MachOFile.cpp#L690), which is used for tracing in debug mode [causing](https://github.com/PureDarwin/dyld/blob/56cd028e61d0d487e5b604eb6bd2c5d577b24241/dyld3/ClosureBuilder.cpp#L370) the dl to be marked as [unloadable](https://github.com/PureDarwin/dyld/blob/56cd028e61d0d487e5b604eb6bd2c5d577b24241/dyld3/APIs.cpp#L816)
=> Fail if libnethack is resident before dlopening.

include/nleobs.h, nle/env/base.py, nle/nethack/nethack.py, nle/scripts/play.py, nle/tests/test_envs.py, src/nle.c, win/rl/pynethack.cc
An xlogfile is a logfile that gives details of the episodes that have
just passed (https://nethackwiki.com/wiki/Xlogfile).  These were
previously being generated in the HACKDIR (temporary var dir). By
setting the SCOREPREFIX and touching the file, you can can change the
path that the file (always ending 'xlogfile') is generated.
NB: There is a lock based on fnctl on the logfile. To avoid multiple
nles in different trying to write to the same file (with the same savedir)
we prepend the process number, like ttyrecs. For writing to same savedir
within same process, an id should be added to both ttyrec and xlogfile.
This can be done in future (along with relabelling ttyrec to ttyrec2).
The log file records all COMPLETED episodes (in the NetHack sense),
since it derives from the features used …
=> Add an xlogfile to the generation of the ttyrecs.

include/nleobs.h, src/nle.c, src/topten.c, win/rl/pynethack.cc
This will make it easier for users to find which ttyrecs correspond to
which metadata.  Xlogfiles are only written to with natural endings; not
guaranteed if you call "reset" before "done" is ready. This means if
there is a panic and drop a game, you will not get alignment between
your ttyrec reset number and xlogfile row. This adds an explicit link.
NB: This only works because in nle (vs typical NetHack), we play the
whole game in _one_ ttyrec.
=> Add the filepath of the ttyrec if it exists to the xlogfile.

nle/dataset/populate_db.py
ttyrecname=<filename> when writing ttyrecs.
=> Populate database using the files in xlogfile

nle/tests/test_envs.py, setup.py
NLE's interface does not pass new gym 0.24.0s checks. We temporarily
pin version while fix is in place.
=> Pin gym to 0.23.0 temporarily.

nle/dataset/db.py, nle/dataset/populate_db.py
We adjust the logging for db.py to be with a specific logger, and
populate_db methods now print. This is because populate methods should
happen very infrequently and should be logged loudly.
=> Adjust logging for populate db.

nle/dataset/db.py
Maybe this is overkill, but i think it enables a good idiom:
```python
import nle.dataset as nld
if not nld.db.exists():
nld.db.create()
nld.add_nledata_directory(path_to_dir, name)
```
=> Add an `exists` method

nle/tests/test_envs.py, src/nle.c
=> Test and fix for issue 333.

.pre-commit-config.yaml
flake8 has been moved from gitlab to github.
=> Fixing flake8 repo link in pre-commit hook
