facebookresearch/nle

- .github/workflows/test_and_deploy.yml
- .github/workflows/test_package.yml
Notes:
- The PyPI workflow just checks for installation (and presence of the nethack binary). We will be able to add tests later once we update `setup.py`.
- Example artefacts: https://github.com/facebookresearch/nle/actions/runs/96887011
> Implement PyPI daily workflow and artefacts generation

- nle/scripts/play.py
And actually make use of `--max-steps`.
> Fix action selection in play script for nethack mode

- .github/pr-labeler.yml
- .github/release-drafter.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/release-drafter.yml
This PR adds:
- Automatic labelling of PRs based on wildcards
- Continuous release drafting
> Add some workflows for automatic PR management

- README.md
MineRL is a successor to Malmo and it would be wonderful if you all would be willing to include it here.
> Adding a related Minecraft environment

- nle/env/base.py
- nle/scripts/play.py
> Allow kicking

- nle/scripts/plot.py
- add documentation, especially examples
- separate collect_logs function from the multi-plot utility (so can be called from elsewhere, e.g. hiplot later on)
- add shuffle option
> update plot.py with examples and utility fixes

- nle/env/base.py
- nle/env/tasks.py
> Do step check outside of _is_episode_end

- nle/dashboard/package-lock.json
As per [relevant CVE](https://nvd.nist.gov/vuln/detail/CVE-2020-7598) and https://github.com/advisories/GHSA-vh95-rmgr-6w4m
> Update minimist to latest version

- .circleci/config.yml
- Files.nle
- nle/scripts/nh-clean-install
- setup.py
- sys/unix/hints/linux
- sys/unix/hints/linux-nle
- sys/unix/hints/macosx
- sys/unix/hints/macosx-nle
This is done to allow us to clean up these hints without merge issues (in another PR :) ).
> Create NLE hint files, and restore originals to NH 3.6.6

- README.md
Changes available to view at: https://github.com/facebookresearch/nle/blob/chore/update-bib/README.md
> Add arXiv link and update bib

- nle/env/tasks.py
I'm not sure about the nomenclature here: `always` vs `constant` is far from obvious.
> Define a new penalty_mode, "always", and make it the default.

- nle/env/base.py
Reason appears to be not getting out of menus after all (mainly "eat").
I wonder why/how this worked before.
> Attempt to fix #41: "smooth quitting of game failed".

- nle/nethack/nethack.py
This makes their creation independent on pwd at runtime and may be beneficial in situations where the archive file is stored on NFS.
> Create temporal ttyrecs inside temporal HACKDIR.

- nle/nethack/nethack.py
- nle/tests/test_envs.py
Avoid pushing more and more stuff to wizkit with each reset of the environment.
> Fix writing a wizkit file.

- nle/nethack/nethack.py
Thanks to @yobibyte for pointing out we don't do this; this used to happen but apparently I screwed it up.
Since libnethack cd's into vardir we have to get out of there again. Ideally, we should make libnethack not cd anywhere.
> Remove temporary directory

- README.md
Hotfix to fix link to architecture doc. Tested just now.
> Hotfix link

- nle/tests/test_nethack.py
> Adding noop deflakes test.

- nle/scripts/play.py
- win/rl/winrl.cc
> Fix blstats, again

- CMakeLists.txt
- nle/env/base.py
- nle/nethack/nethack.py
- nle/tests/test_envs.py
- nle/tests/test_nethack.py
- src/nle.c
- win/rl/pynethack.cc
Also fix misc test again and make installation a bit quieter.
> Make NLE only run bzip2 when necessary

- nle/env/base.py
> Quick typo correction

- README.md
Documentation at https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge
> Add GH Actions shield/badge.

- nle/tests/test_nethack.py
- win/rl/pynethack.cc
This helps with entities like trees.
As discussed in https://discord.com/channels/831140205251526676/831140282912211055/870779057401389057
> Add symdef Python class.

- nle/nethack/nethack.py
The tempfile.NamedTemporaryFile for the shared library (on MacOS)
was currently not removed before its parent directory. This change
should fix that. It also makes sure the C++ pynethack object gets
closed in all cases.
This fixes an ignored exception when running e.g. scripts/test_raw_nethack.py.
> Close Nethack instance via finalizer.

- .github/workflows/test_and_deploy.yml
- README.md
- nle/tests/test_system.py
And misc. changes.
Turns out #254 only shows up on my local machine (?!).
> Tests for NLE when using two environments sequentially or in threads

- nle/env/tasks.py
- nle/tests/test_nethack.py
> Fix NetHackScout environment following #179.

- nle/nethack/actions.py
- nle/nethack/nethack.py
- nle/tests/test_nethack.py
Also add `time` to `NETHACKOPTIONS`.
Also add the wizard commands with keyboard shortcuts, fixing #281.
> Add missing see* actions (e.g., '$') and test.

- CITATION.cff
Somewhat inconvienient, but following
https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#credit-redirection
> Add CITATION.cff file.

- nle/scripts/read_tty.py
Surprisingly tricky to get the proper git-diff behaviour, but also kinda fun: https://github.com/git/git/blob/master/pager.c
> Use pager in read_tty.py by default, like git-diff.

- nle/dataset/dataset.py
> Ensure that subselect sql query still only selects from the specified

- README.md
Added information about the NLE language wrapper in the README.md
> Info about the NLE language wrapper in the README.md

- .flake8
- .github/workflows/test_and_deploy.yml
- nle/tests/test_converter.py
> Fix CI by fully specifying Python env and adjusting range on flakey
